### ISSUE TITLE
Sactum like API authorization

### ISSUE THREAD

**Issue by microwavekonijn** [ps2alerts/api#12]
We are going to take a similar approach to what Laravel Sanctum offers for Laravel. We are going to allow our the SPA to directly communicate to our API without the need of an API key using a csrf token, other applications need an API key to get access to the API.

What this will not do is make it so that our API gets used by only people we allow, instead it allows us to track who is using our API and in what way. It will also allows us to later add an authentication system for user specific features.

The system requires the following features:
- An route to make our SPA stateful by setting the necessary cookies;
- A middleware function that tries to verify the csrf token, or the API key;
- The system needs to be headless as in you can't store the csrf tokens;
- Optional: A way to revoke tokens (thought I don't think it is possible).

You can probably just copy the code from any middleware that implements the csrf feature and extend it with an API key validation if the csrf token is not set.

**Comment by Maelstromeous** [comment]
Two concerns:

1) The Website must not have access to any Update or Delete operaitons for the API due to exclusively allowing access to read without API keys.

2) We will absolutely need a way to revoke tokens. We also should be concerned about rate limits.

**Comment by microwavekonijn** [comment]
1. There will not be any, and even when there are you will need authentication with the appropriate privileges.
2. I don't think it is possible, it is more to have some barrier in place and being able to track clients that use the API. The main problem is that anyone is able to access the endpoints unless you require authentication. When there is abuse the only thing that you can do is block the ip. Ratelimits definitely, but that is not related to this.

**Comment by Maelstromeous** [comment]
Deprioritising due to people being sensible using the API (or more likely, no-one knows it really exists except a few)
