### ISSUE TITLE
Setup handler for incoming messages from the websocket

### ISSUE THREAD

**Issue by microwavekonijn** [ps2alerts/api#14]
The API will listen to messages send over by RabbitMQ from the websocket. It in turn will take these messages and update values inside the database. Depends on #13 to be finished first.

**Comment by Maelstromeous** [comment]
Related: https://github.com/ps2alerts/websocket/issues/127

Data should match the following pattern.

```
{
  "operation": "create",
  "type": "instance",
  "body": {
    "instanceId:",
    ... etc to match the model
   }
}
```

We also need to determine if we're going to use multiple queues (there's no reason why we can't) or we funell all websocket -> API messages in a singular queue then pick them out at the consumer level.

**Comment by microwavekonijn** [comment]
Operations and type seems to be unnecessary, the queue will only contain those kind of messages anyway. We will have to figure out some kind of format that works for both the websocket as the api with the consideration that the api just updates one document.

**Comment by Maelstromeous** [comment]
Well the message that is sent to Rabbit is JSON, so it can be whatever really. Don't we need a way of distinguishing what kind of message it's getting though? Otherwise how can you tell from a message what is "hey you, create alert, here's the deets" versus a "hey, this guy died, record it will ya"?

**Comment by microwavekonijn** [comment]
Oh wait, I read that wrong. Though do we want to keep things generic or not. Also, small note, with queues the websocket will be in charge of creating unique ids.

**Comment by Maelstromeous** [comment]
> unique ids.

I believe by this you mean the message IDs? I was more on about the instance IDs in the example :)

**Comment by microwavekonijn** [comment]
More like with a rest post request you get the id of an inserted resource back, that is not possible with a pub-sub system as there is no feedback.

**Comment by Maelstromeous** [comment]
True, however I don't believe we'll need responses for the majority of websocket generated data. I see the websocket as sending messages like UDP does, fires them off with the hopes it gets processed eventually.

I believe certain resources we **will** need a response from and cannot be message queued, specifically start / end instance - as this is held within the websocket memory. We will also need to modify the boot of the socket to read from the API for a list of active instances like it does now.

Primary reason why I'm opting for maintaining the active state within the websocket is down to volume. Requesting the active instance list on every single event will be utterly madness.

**Comment by microwavekonijn** [comment]
Yes, excatly. For those instances the websocket need to generate the ids. I was thinking of an extra queue from the api to the websocket, however the websocket need to start collecting right away and cannot wait for the api. The only reason you add that queue is for custom events for instance.

**Comment by microwavekonijn** [comment]
Based on nestjs the messages should have the following format:
```js
{
  "pattern": "model_name".
  "payload": [
    {...matcher},
    {...pathed data}
  ]
}
```

**Comment by Maelstromeous** [comment]
This is now complete and is functioning. We now need to add the event subscribers into each controller / endpoint where they will be inserted using the same model / code as a normal CRUD create would. #21
