### ISSUE TITLE
Websocket server

### ISSUE THREAD

**Issue by microwavekonijn** [ps2alerts/api#15]
The server will be used to send out updates in real time to the clients. The protocol will work as follows:
- The client connects to the websocket and receives a collection of all available rooms/channels;
- The client subscribes to a room/channel, upon subscribing it receives a current state of events;
- The client will hence forward receive partial objects with updated states that it is able to merge with the initial state it received.

Other requirements:
- Only use the websocket for active alerts/events, or use it for everything(don't know if there is a downside when it comes to performance/complexity for clientside code);
- Active alerts/events will be updated in realtime requiring an active system to handle this flow of information;
- An important aspect is the order of operations of the code. In other words: a client should not miss information or have faulty information as said information was updated while it was being retrieved nor should it have to wait until said faulty information get replaced with new information.

Might tie in nicely with the idea of removing more detailed data later down the line. E.g. kills of a player: just have an array of killed characters with details. You can then quickly tell what version of the data you have got and get the relevant data that is missing. It can help create a more lazy system.

**Important note**

The API can run multiple instances meaning that one instance will not receive all messages from RabbitMQ.

**Comment by Maelstromeous** [comment]
> Active alerts/events will be updated in realtime requiring an active system to handle this flow of information;

This can just be it's own channel. Browsers are able to open multiple websocket connections, so we'd just have a realtime monitor channel which is always open and always updates the monitor on the site.

> An important aspect is the order of operations of the code. In other words: a client should not miss information or have faulty information as said information was updated while it was being retrieved nor should it have to wait until said faulty information get replaced with new information.

Unless we add some sort of "sync" call, this will happen. You will get the rare occasion where a death isn't emitted twice or you get death events immediately after an alert finishes. In the old site, once the alert finished, I forced a refresh on the browser (literally just `window.replace(<current url>))` and then it would always be in sync. However, if we were to do this in real time, we either need to accept that a certain number of kills will get lost, as there is a period where the page is loading, the website is subscribing and isn't receiving current events.

**Comment by microwavekonijn** [comment]
For the first point, I want to make kind of a subscription system like the census event stream. Each connection will have their own subscriptions, even thought 2 connections come from the same client.

The point I wanted to raise there was that the design of the system needs to be so that this doesn't happen. Also if an alert ended we can keep on receiving and processing data regardless whether the instance has ended(this holds for the API as well as the website), the responsibility of that lies with the websocket.

**Comment by Maelstromeous** [comment]
> Also if an alert ended we can keep on receiving and processing data regardless whether the instance has ended

Biiig nono imo, if we're on the alert page we shouldn't be collecting data on other instances and should stop once the instance ends. Reason being for this, primarily, is volume. We need to be able to subscribe and unsubscribe from certain instances at will based on what we're looking at. Consider how many messages we're going to get in real time, it could quite easily be in the thousands within a second if we're watching all of the other alerts at the same time. I kinda wish I was kidding.

**Comment by microwavekonijn** [comment]
I understand, but that is not the responsibilty of the API. Any message in the queue is good, as the websocket added it. Mostly what I was aiming at was where an alert ended message is added to the queue before an kill message that belongs to that alert for instance. The API is dumb it can't figure out if it needs to handle a message from the queue, so it handles them all or none, so it handles them all.

**Comment by Maelstromeous** [comment]
I think we're talking about slightly different things, I'm talking about syncing at the client website side - we will hit the scenario where certain messages are out of sync, e.g a death after an instance end.

However having said that eventual consistency is fine, as the websocket won't actually add messages for deaths / xp to be stored by the API after the instance ends anyway. So as long as we don't fully terminate the connection on the website code when we get an end message (say terminate it 2 mins after end to let everything catch up) then it won't be an issue imo.

**Comment by microwavekonijn** [comment]
Oh, like that. My proposal was when you open the website you also open a websocket connection on which you can tell the server what info you like to start and stop receiving.

**Comment by Maelstromeous** [comment]
Yes, I'm on about it at the instance / alert level. I'm all for a subscriber system, but we need to be able to swap between alerts as the user browses the site, so I guess similar to census except actually works and you don't need a master degree to figure it out.

**Comment by microwavekonijn** [comment]
So like census, but it actually works. I like it

**Comment by Maelstromeous** [comment]
@microwavekonijn Guessing we didn't get anywhere with this? Guessing you're not up to it? If so, feel free to close

**Comment by microwavekonijn** [comment]
Yeah, polling was a much simpler solution requiring less work.

**Comment by Maelstromeous** [comment]
I'll delete the repo as well. RIP
