### ISSUE TITLE
Implement REST read endpoints

### ISSUE THREAD

**Issue by microwavekonijn** [ps2alerts/api#16]
Expose the data directly through an http endpoint.

Endpoints currently in mind:

# Instances

Exposes the currently active instances, and provides a history with a paginated list. Needs to be filterable by server, date/time and zone.

* [x] GET instance
* [x] GET instances list (paginated) by filters world / zone / faction victory
* [x] GET active instances
* [x] GET instances by world
* [x] GET instances by zone (maybe)

# Aggregates

Path: `<ROOT>/aggregates/`

## Global

Path: `<ROOT>/aggregates/global/`

### Global Character Aggregate

Path: `<ROOT>/aggregates/global/character`

Exposes statistics for each character on a world.

* [x] GET single char ID
* [x] GET list of characters
* [x] GET list of characters by world ID
* [ ] GET list of characters sorted by metric (e.g. kills)
* [ ] GET list of characters by world ID sorted by metric

### Global Class Aggregate

Path: `<ROOT>/aggregates/global/class`

Exposes statistics for particlar classes on a world

* [x] GET single loadout (class) ID globally
* [x] GET single loadout ID for world
* [x] GET all loadouts
* [x] GET all loadouts by world

### Global Facility Control

Path: `<ROOT>/aggregates/global/facility`

* [x] GET single facility ID globally
* [x] GET single facility ID for world
* [x] GET all facilities by world
* [ ] GET all facilities by zone
* [ ] GET all facilities by world and zone

### Global Facition Combat

Path: `<ROOT>/aggregates/global/faction`

* [ ] GET by faction globally
* [ ] GET by faction for world
* [x] GET all factions for world

Potentially GET for all factions by instances on a zone, not sure if that's useful or not. Might have to do a zone combat metric at some point if people want it. Could do it via an Mongo aggregate.

### Global Outfits

Path: `<ROOT>/aggregates/global/outfit`

* [x] GET by outfit ID (potentially might need world ID due to PS4 US and PS4 EU)
* [x] GET list of outfits by world
* [ ] GET list of outfits globally sorted by metric
* [ ] GET list of outfits by world sorted by metric

### Global Weapons

Path: `<ROOT>/aggregates/global/weapon`

* [x] GET by weapon ID
* [x] GET by weapon ID by world
* [x] GET list of weapons globally
* [x] GET list of weapons by world
* [ ] GET list of weapons globally sorted by metric
* [ ] GET list of weapons by world sorted by metric

## Instance

Path: `<ROOT>/aggregates/instance/`

### Instance Character Aggregate

Path: `<ROOT>/aggregates/instance/character`

Exposes statistics for each character for an instance.

* [x] GET single char ID within instance
* [x] GET list of characters within instance
* [ ] GET list of characters sorted by metric (e.g. kills) within instance

### Instance Class Aggregate

Path: `<ROOT>/aggregates/instance/class`

* [x] GET single loadout (class) ID within instance
* [x] GET all loadouts within instance

### Instance Facility Control

Path: `<ROOT>/aggregates/instance/facility`

* [x] GET single facility ID within instance
* [x] GET all facilities within instance

### Instance Facition Combat

Path: `<ROOT>/aggregates/instance/faction`

* [x] GET by faction within instance
* [x] GET all factions within instance

### Instance Outfits

Path: `<ROOT>/aggregates/instance/outfit`

* [x] GET by outfit ID within instance
* [x] GET list of outfits within instance
* [ ] GET list of outfits within instance sorted by metric

### Instance Population Aggregate

Path: `<ROOT>/aggregates/instance/population`

Gets the population history as detected by the Aggregator for the instance

* [x] GET list of population metrics within instance, sorted by time ASC

### Instance Weapons

Path: `<ROOT>/aggregates/instance/weapon`

* [x] GET by weapon ID within instance
* [x] GET list of weapons within instance
* [ ] GET list of weapons within instance sorted by metric

**Comment by Maelstromeous** [comment]
Ideally this needs to be fleshed out with documentation of what we're going to send etc.

I would recommend Swagger / OpenAPI spec for this if it was PHP, not sure if there is such a thing for JS. Hopefully NestJS has some means of generating documentation via code.

**Comment by microwavekonijn** [comment]
Look at that :D https://docs.nestjs.com/openapi/introduction

Never worked with it though, so I would just start implementing controllers to deal with this.

**Comment by Maelstromeous** [comment]
Updated ticket description with full list of endpoints I think we'd need for exposing most of the data

**Comment by zhenghung** [comment]
Following applies to both Global and Instance:

What is zone in facilitycontrol? Because that's not a property in the aggregate.
Also, for FactionCombat, one entity contains all 4 faction in a world/instance. So if we want an endpoint for only one faction, it wouldn't be returning the the aggregate but rather the embedded entity CombatStats.

**Comment by Maelstromeous** [comment]
@zhenghung Can you update this with what you consider complete and tested for the REST endpoints?

**Comment by Maelstromeous** [comment]
This is essentially done minus sorting / pagination which will be handled hopefully by #64
