### ISSUE TITLE
Outfitwars support

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/api#312]
Support for https://github.com/ps2alerts/aggregator/issues/578 and https://github.com/ps2alerts/website/issues/460

Will require new endpoints or current ones adjusting to accept a type of metagame instance.

## Aggregator support

- We will need the ability to process aggregations, **but** they must now accept a type e.g. `type: outfitwarsterritory`.
- Endpoints will need to be adjusted to allow the website to query by a type of instance. By default it should serve `TerritoryInstance`, but optionally we should able to specify the instance type for `OutfitWarsTerritoryInstance`.

**Comment by ryanjsims** [comment]
# API Support
* Will need an `outfitwar-match` endpoint with GET, POST, PUT, DELETE operations - all write methods will be behind auth
    * A match will have 2 outfits, an OutfitWarsTerritoryInstance ID starting out null, and a winning outfit starting out null

**Comment by Maelstromeous** [comment]
Instance records will now have a "instanceType" attached to them, to denote the difference between the two instance types. This also enables us to better filter and report upon other metagame types in the future.

The below has been added to the `outfitwars` brancn on the constants

```
export enum Ps2alertsEventType {
    LIVE_METAGAME = 1,
    OUTFIT_WARS_AUG_2022 = 2,
}
```
